apiVersion: apps/v1
kind: Deployment
metadata:
  name: nlb-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nlb-app
  template:
    metadata:
      labels:
        app: nlb-app
    spec:
      containers:
        - name: nlb-app
          image: davidegalifi/quick-service:latest
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 128Mi
              cpu: 100m
          env:
          - name: MESSAGE
            value: "Hello from NLB app"
---
# Supported annotations
# https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.7/guide/service/annotations/
apiVersion: v1
kind: Service
metadata:
  name: nlb-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    # service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: http
  selector:
    app: nlb-app